"""empty message

Revision ID: 48e2177341c6
Revises: 99a0dac00e4d
Create Date: 2021-01-27 22:33:24.480752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48e2177341c6'
down_revision = '99a0dac00e4d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('logistic_model',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=True),
    sa.Column('feature', sa.String(length=120), nullable=True),
    sa.Column('coef', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('logistic_model')
    # ### end Alembic commands ###
